const axios = require("axios");

// ================= ENV VARIABLES =================
const USER_ID = process.env.CLUBKONNECT_USER_ID;
const API_KEY = process.env.CLUBKONNECT_API_KEY;

const AIRTIME_URL = process.env.CLUBKONNECT_AIRTIME_URL;
const DATA_URL = process.env.CLUBKONNECT_DATA_URL;
const DISCOUNT_URL = process.env.CLUBKONNECT_DISCOUNT_URL;

// ================= HELPER =================
function generateRequestID() {
  return (
    "BK9JA_" +
    Date.now() +
    "_" +
    Math.floor(Math.random() * 10000)
  );
}

// ================= CLUBKONNECT SERVICE =================
const clubKonnectService = {

  // ==================================================
  // GET AIRTIME SERVICES
  // ==================================================
  getAirtimeServices: async () => {
    try {
      const response = await axios.get(DISCOUNT_URL, {
        params: {
          UserID: USER_ID,
        },
      });

      return response.data;
    } catch (err) {
      return {
        error: err.response?.data || err.message,
      };
    }
  },

  // ==================================================
  // BUY AIRTIME
  // ==================================================
  buyAirtime: async ({
    network,
    amount,
    phone,
    request_id,
  }) => {

    const requestId = request_id || generateRequestID();

    try {
      const response = await axios.get(AIRTIME_URL, {
        params: {
          UserID: USER_ID,
          APIKey: API_KEY,
          MobileNetwork: network,
          Amount: amount,
          MobileNumber: phone,
          RequestID: requestId,
        },
      });

      const result = response.data;

      console.log(
        "CLUBKONNECT AIRTIME RESPONSE:",
        JSON.stringify(result)
      );

      /*
       * ClubKonnect/Nellobyte can return statuses such as:
       *
       * ORDER_COMPLETED
       * ORDER_RECEIVED
       * ORDER_ONHOLD
       * ORDER_FAILED
       *
       * Do not confuse HTTP 200 with transaction success.
       */

      const status = String(result?.status || "").toUpperCase();

      if (
        status === "ORDER_COMPLETED" ||
        result?.statuscode === "100"
      ) {
        return {
          status: "success",
          requestId,
          reference: result?.orderid || result?.reference || requestId,
          message: result?.remark || "Airtime purchase successful",
          raw: result,
        };
      }

      return {
        status: "failed",
        requestId,
        error: result?.remark || result?.status || "Airtime purchase failed",
        raw: result,
      };

    } catch (err) {

      console.error(
        "ClubKonnect airtime error:",
        err.response?.data || err.message
      );

      return {
        status: "failed",
        requestId,
        error: err.response?.data || err.message,
      };
    }
  },

  // ==================================================
  // BUY DATA
  // ==================================================
  buyData: async ({
    network,
    dataplan,
    phone,
    request_id,
  }) => {

    /*
     * IMPORTANT:
     * Use the request ID generated by the controller.
     * Do NOT generate another ID here.
     */
    const requestId = request_id || generateRequestID();

    try {

      const response = await axios.get(DATA_URL, {
        params: {
          UserID: USER_ID,
          APIKey: API_KEY,
          MobileNetwork: network,
          DataPlan: dataplan,
          MobileNumber: phone,
          RequestID: requestId,
        },
      });

      const result = response.data;

      console.log(
        "=========================================="
      );
      console.log(
        "CLUBKONNECT DATA RESPONSE:"
      );
      console.log(
        JSON.stringify(result, null, 2)
      );
      console.log(
        "=========================================="
      );

      const status = String(
        result?.status || ""
      ).toUpperCase();

      /*
       * SUCCESS
       *
       * ClubKonnect/Nellobyte commonly uses
       * ORDER_COMPLETED for a completed transaction.
       */
      if (
        status === "ORDER_COMPLETED" ||
        result?.statuscode === "100"
      ) {

        return {
          status: "success",
          requestId,

          reference:
            result?.orderid ||
            result?.reference ||
            requestId,

          message:
            result?.remark ||
            "Data purchase successful",

          raw: result,
        };
      }

      /*
       * Pending / received / on hold
       *
       * IMPORTANT:
       * Do NOT refund immediately if the provider
       * has accepted the transaction but has not
       * returned final completion yet.
       */
      if (
        status === "ORDER_RECEIVED" ||
        status === "ORDER_ONHOLD"
      ) {

        return {
          status: "pending",
          requestId,

          reference:
            result?.orderid ||
            result?.reference ||
            requestId,

          message:
            result?.remark ||
            "Data purchase is being processed",

          raw: result,
        };
      }

      /*
       * Actual provider failure
       */
      return {
        status: "failed",
        requestId,

        error:
          result?.remark ||
          result?.status ||
          "ClubKonnect data purchase failed",

        raw: result,
      };

    } catch (err) {

      console.error(
        "=========================================="
      );

      console.error(
        "CLUBKONNECT DATA ERROR:"
      );

      console.error(
        err.response?.data || err.message
      );

      console.error(
        "=========================================="
      );

      return {
        status: "failed",
        requestId,
        error: err.response?.data || err.message,
      };
    }
  },

  // ==================================================
  // VERIFY TRANSACTION
  // ==================================================
  verifyTransaction: async (requestId) => {

    try {

      const response = await axios.get(
        "https://www.nellobytesystems.com/APIQuery.asp",
        {
          params: {
            UserID: USER_ID,
            APIKey: API_KEY,
            RequestID: requestId,
          },
        }
      );

      return response.data;

    } catch (err) {

      return {
        error:
          err.response?.data || err.message,
      };
    }
  },
};

module.exports = clubKonnectService;